name: Deploy AppSync API with CloudFormation

on:
  push:
    branches:
      - master # Adjust the branch name as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # Adjust the region as necessary

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body /template.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name potato \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              client_id=${{ secrets.CLIENT_ID }} \
              client_secret=${{ secrets.CLIENT_SECRET }} \
              grant_type=${{ secrets.GRANT_TYPE }}
              api_url=${{ secrets.API_URL }}
              login_url=${{ secrets.LOGIN_URL }}

      - name: Verify Stack Update
        run: |
          aws cloudformation describe-stacks --stack-name your-appsync-stack-name
